export const REGIONS=['Ahmedabad East','Ahmedabad West','Gandhinagar','Vadodara'];
export const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,Number(v)||0));
export const average=values=>values.length?Math.round(values.reduce((a,b)=>a+Number(b||0),0)/values.length):0;
export const millis=v=>v?.toMillis?.() ?? (typeof v?.seconds === 'number' ? v.seconds * 1000 + (v.nanoseconds || 0) / 1e6 : undefined) ?? (v instanceof Date?v.getTime():typeof v==='number'?v:Date.parse(v)||0);
export const dateText=v=>millis(v)?new Date(millis(v)).toLocaleString('en-IN'):'Not recorded';
export const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Existing renderers use HTML templates; escape all Firestore-derived text at their boundary.
export function safeView(value){if(typeof value==='string')return escapeHTML(value);if(Array.isArray(value))return value.map(safeView);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,safeView(v)]));return value;}
export function message(text,error=false){let el=document.getElementById('connectionStatus');if(!el){el=document.createElement('p');el.id='connectionStatus';el.className='page-subtitle';el.setAttribute('role','status');(document.querySelector('.page-header')||document.querySelector('main')||document.body).prepend(el);}el.textContent=text;el.dataset.error=String(error);}
export function errorText(e){return ({'permission-denied':'Permission denied. Check your account and deployed Firestore rules.','unavailable':'Network unavailable. Reconnect and retry.','auth/invalid-credential':'Email or password is incorrect.','auth/email-already-in-use':'This email already has an account. Sign in instead.','auth/weak-password':'Use a password with at least 6 characters.','auth/invalid-email':'Enter a valid email address.','auth/too-many-requests':'Too many attempts. Please try again later.','auth/network-request-failed':'Unable to reach Firebase. Check your connection.'})[e?.code]||e?.message||'Something went wrong. Please retry.';}
export function clearInspector(){for(const el of document.querySelectorAll('[id^="detail"]'))if(!el.children.length)el.textContent='—';for(const id of ['evidenceList','checklist','skillList','memberList','eventTimeline','reasonBox','rootCause','assignmentTitle','assignmentDescription']){const el=document.getElementById(id);if(el)el.textContent='No matching records';}}
