import { average, millis, dateText, clamp } from './utils.js';
import { WEIGHTS } from './risk-engine.js';
export function distance(a,b){const rad=x=>x*Math.PI/180;const lat=rad(b.latitude-a.latitude),lon=rad(b.longitude-a.longitude);return 6371*2*Math.asin(Math.min(1,Math.sqrt(Math.sin(lat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(lon/2)**2)));}
export function preposition(state){return state.assets.filter(a=>a.riskLevel!=='Stable').map(a=>{const ready=state.crews.filter(c=>c.status==='Ready'&&c.availability&&!c.assignedOrderId&&c.region===a.region&&c.skills.includes(a.type)).sort((x,y)=>distance(x,a)-distance(y,a));const c=ready[0];return {assetId:a.assetId,crewId:c?.crewId,area:a.area,risk:a.riskLevel,score:a.riskScore,explanation:c?`${c.name}: ${distance(c,a).toFixed(1)} km, matching skill, available in region; weather exposure ${state.weatherSnapshots[0]?.weatherRiskScore??0}/100.`:'No available crew with matching skill in this region.'};}).sort((a,b)=>b.score-a.score);}
export function buildView(s,page){
 const weather=s.weatherSnapshots.slice().sort((a,b)=>millis(b.timestamp)-millis(a.timestamp))[0]||{condition:'Unavailable',temperature:'—',rainfall:0,windSpeed:0,humidity:0,weatherRiskScore:0};
 const weatherText=`${weather.condition} · ${weather.temperature}°C (${weather.source==='open-meteo'?'current':'demo'})`;
 const byPrediction=new Map(s.predictions.map(p=>[p.assetId,p]));
 const byAsset=new Map(s.assets.map(a=>[a.assetId,a]));
 const latest=new Map();for(const r of s.sensorReadings)if(!latest.has(r.assetId)||millis(r.timestamp)>millis(latest.get(r.assetId).timestamp))latest.set(r.assetId,r);
 const assets=s.assets.map(a=>{const p=byPrediction.get(a.assetId),r=latest.get(a.assetId),risk=p||a;return {id:a.assetId,location:a.area,area:a.area,type:a.type,risk:risk.riskLevel||'Stable',score:clamp(risk.riskScore),probability:clamp(risk.failureProbability),health:clamp(a.healthScore),impact:risk.gridImpact||a.gridImpact,signal:p?.predictedFailureMode||'Prediction unavailable',maintenance:dateText(a.lastMaintenance),telemetry:a.telemetryOnline&&r?'Online · simulated':'Offline / missing',recommendation:p?.recommendedAction||'No prediction available. Review sensor history.',action:p?.recommendedAction||'Review asset',weather:weather.condition,lat:a.latitude,lng:a.longitude,reason:p?.predictedFailureMode||'No prediction',sensors:r?[['Temperature',clamp(r.temperature),`${r.temperature}°C`],...(r.oilTemperature===null?[]:[['Oil temperature',clamp(r.oilTemperature/1.2),`${r.oilTemperature}°C`]]),['Vibration',clamp(r.vibration*10),`${r.vibration} mm/s`],['Partial discharge',clamp(r.partialDischarge/5),`${r.partialDischarge} pC`],['Oil quality',clamp(r.oilQuality),r.oilQuality===null?'N/A':`${r.oilQuality}/100`],['Load',clamp(r.loadPercentage),`${r.loadPercentage}%`],['Anomaly',clamp(r.anomalyScore),`${r.anomalyScore}/100`]]:[]};}).sort((a,b)=>b.score-a.score);
 const predictions=s.predictions.filter(p=>byAsset.has(p.assetId)).sort((a,b)=>b.riskScore-a.riskScore).map(p=>({id:p.assetId,area:byAsset.get(p.assetId).area,type:byAsset.get(p.assetId).type,risk:p.riskLevel,score:p.riskScore,probability:p.failureProbability,confidence:p.confidence,impact:p.gridImpact,window:`${p.predictionWindowHours} hours`,headline:p.predictedFailureMode,explanation:`Weighted heuristic; ${p.failureProbability}% is an uncalibrated risk proxy. Generated ${dateText(p.generatedAt)}. Confidence measures input completeness.`,action:p.recommendedAction,evidence:(p.evidence||[]).map(e=>[e.feature,String(e.value),`Normalized ${e.normalizedScore}/100; weight ${Math.round(e.weight*100)}%`])}));
 const orders=s.maintenanceOrders.map(o=>({order:o.orderId,asset:o.assetId,area:byAsset.get(o.assetId)?.area||'Unknown asset',type:byAsset.get(o.assetId)?.type||'Unavailable',priority:o.priority,risk:`${byPrediction.get(o.assetId)?.failureProbability??o.failureRisk}%`,impact:byPrediction.get(o.assetId)?.gridImpact||o.gridImpact,due:dateText(o.dueAt),crew:s.crews.find(c=>c.crewId===o.assignedCrewId)?.name||'Unassigned',status:o.status,summary:o.summary,reason:o.aiReason,checklist:(o.checklist||[]).map(c=>[c.title,c.description])})).sort((a,b)=>Number(b.priority==='Critical')-Number(a.priority==='Critical'));
 const crews=s.crews.map(c=>{const o=s.maintenanceOrders.find(o=>o.orderId===c.assignedOrderId);return {id:c.crewId,code:c.name.split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join(''),name:c.name,area:c.currentArea,state:c.status,eta:'Not estimated',size:`${c.members.length} technicians`,load:c.assignedOrderId?'1 active order':'No active order',priority:o?.priority||'Stable',assignment:o?.assetId||'Standby',description:o?.summary||`${c.latitude}, ${c.longitude} · ${c.availability?'Available':'Unavailable'}`,skills:c.skills||[],members:(c.members||[]).map(m=>[m.name.split(/\s+/).map(x=>x[0]).join(''),m.name,m.role])};});
 const incidents=s.incidents.slice().sort((a,b)=>Number(a.status==='Resolved')-Number(b.status==='Resolved')||millis(b.startedAt)-millis(a.startedAt)).map(i=>({id:i.incidentId,asset:i.assetId,area:byAsset.get(i.assetId)?.area||'Unknown asset',type:byAsset.get(i.assetId)?.type||i.type,severity:i.severity,status:i.status,detected:dateText(i.startedAt),impact:`${i.affectedLoadMW} MW · ${i.customersAffected} customers`,crew:s.crews.find(c=>s.maintenanceOrders.some(o=>o.assetId===i.assetId&&o.assignedCrewId===c.crewId))?.name||'Unassigned',title:i.title,summary:i.description,rootCause:`${i.weatherRelated?'Weather-related':'No weather relationship reported'} · current asset risk ${byPrediction.get(i.assetId)?.riskScore??byAsset.get(i.assetId)?.riskScore??'—'}/100. Cause requires field verification.`,timeline:[[dateText(i.startedAt),i.severity,i.title,'Demo incident opened'],...(i.resolvedAt?[[dateText(i.resolvedAt),'Normal','Resolved','Operator marked resolved']]:[])]}));
 const critical=assets.filter(a=>a.risk==='Critical').length,elevated=assets.filter(a=>a.risk==='Elevated').length,ready=s.crews.filter(c=>c.status==='Ready'&&c.availability).length,active=s.incidents.filter(i=>i.status!=='Resolved'),open=s.maintenanceOrders.filter(o=>o.status!=='Completed');
 const center=[s.region?.weatherLocation?.latitude||23,s.region?.weatherLocation?.longitude||72];
 const empty={id:'No assets',area:'—',score:0,probability:0,impact:'—',weather:weather.condition,signal:'No prediction',action:'Seed or add regional data.'};
 const top=assets[0]||empty;
 const v={assets,predictions,orders,crews,incidents,center,zoom:12,total:assets.length,monitored:assets.length,critical,elevated,highRisk:critical+elevated,health:`${average(assets.map(a=>a.health))}%`,gridHealth:`${average(assets.map(a=>a.health))}%`,telemetry:`${assets.length?Math.round(latest.size/assets.length*100):0}%`,coverage:`${assets.length?Math.round(latest.size/assets.length*100):0}%`,confidence:`${average(predictions.map(p=>p.confidence))}%`,weather:weatherText,outageExposure:`${active.reduce((s,i)=>s+i.affectedLoadMW,0).toFixed(1)} MW`,highestZone:top.location||'No assets',regionRiskText:`Weather exposure ${weather.weatherRiskScore}/100. ${critical} critical assets. Demo risk model.`,weatherZone:{center,radius:weather.weatherRiskScore*60},map:{center,zoom:12,weatherCenter:center,weatherRadius:weather.weatherRiskScore*60},focus:{...top,area:top.location||'—',probability:`${top.probability}%`},ai:{title:assets.length?`Prioritize ${top.id}`:'No regional assets',description:'Transparent weighted risk score using simulated telemetry. No trained ML model.',actions:[top.action,'Review evidence and historical sensor trends',`${ready} crews ready for assignment`]},timeline:[12,24,48,72].map(h=>[`${h}h`,s.predictions.filter(p=>p.predictionWindowHours<=h&&p.riskLevel!=='Stable').length,critical?'Critical':elevated?'Elevated':'Stable']),drivers:Object.entries(WEIGHTS).map(([k,w])=>[k,`${Math.round(w*100)}%`,'Documented model weight'])};
 const completed=s.maintenanceOrders.filter(o=>o.status==='Completed').length;
 if(page==='dashboard'){v.weather={short:weatherText,temp:`${weather.temperature}°`,status:weather.condition,rainfall:`${weather.rainfall} mm/h`,wind:`${weather.windSpeed} km/h`,humidity:`${weather.humidity}%`,alert:`Weather exposure ${weather.weatherRiskScore}/100 · ${weather.source==='open-meteo'?'current weather; predictions retain their saved weather snapshot':'simulated weather'}.`};v.crews=crews.map(c=>[c.code,c.name,c.area,c.state]);v.incidents=incidents.slice(0,5).map(i=>[i.severity==='Critical'?'#c4594d':'#c39341',`${i.asset} · ${i.title}`,`${i.status} · ${i.detected}`]);}
 if(page==='maintenance'){v.stats={open:open.length,crews:s.crews.filter(c=>c.assignedOrderId).length,load:'Not estimated',reduction:'Not measured',stabilized:completed,exposure:'Not estimated',...Object.fromEntries([12,24,72].map(h=>[`due${h}`,open.filter(o=>millis(o.dueAt)<=Date.now()+h*3600000).length]))};v.pipeline=['Pending','Assigned','In Progress','Completed'].map((status,i)=>[String(i+1),status,orders.filter(o=>o.status===status).length,'Persisted work orders']);v.resources=crews.map(c=>[c.code,c.name,c.area,c.state]);}
 if(page==='crews'){v.stats={available:ready,deployed:crews.filter(c=>['Assigned','Deployed'].includes(c.state)).length,eta:'Not estimated',technicians:s.crews.filter(c=>c.availability).reduce((n,c)=>n+c.members.length,0),capacity:ready,coverage:`${s.crews.length?Math.round(ready/s.crews.length*100):0}%`,dispatch:'Not measured',closed:completed,sla:'Not measured'};const recommendations=preposition(s);v.coverage=recommendations.slice(0,4).map(r=>[r.area,r.risk,r.score,r.crewId?'Crew available':'No crew available',r.crewId||'—']);v.queue=recommendations.slice(0,4).map(r=>['→',r.assetId,r.explanation,'Recommendation']);}
 if(page==='incidents'){const resolved=s.incidents.filter(i=>i.resolvedAt);v.stats={active:active.length,affected:new Set(active.map(i=>i.assetId)).size,resolution:resolved.length?`${average(resolved.map(i=>(millis(i.resolvedAt)-millis(i.startedAt))/60000))} min`:'Not measured',load:v.outageExposure,customers:active.reduce((n,i)=>n+i.customersAffected,0),critical:active.filter(i=>i.severity==='Critical').length,ack:'Not measured',closed:resolved.length,sla:'Not measured'};v.responseFlow=['Open','Monitoring','Resolved'].map((status,i)=>[String(i+1),status,incidents.filter(x=>x.status===status).length,'Persisted incident status']);v.history=incidents.slice(0,5).map(i=>['#c39341',i.title,i.status,i.detected]);}
 return v;
}
